module.exports = {
    // Genres
    "Action": "動作",
    "Adventure": "冒險",
    "Avant Garde": "前衛",
    "Award Winning": "獲獎作品",
    "Boys Love": "BL",
    "Comedy": "喜劇",
    "Drama": "劇情",
    "Ecchi": "Ecchi", // Often kept as Ecchi or translated as 賣肉/色情 but usually Ecchi is understood by fans or use "粉絲向"
    "Erotica": "成人",
    "Fantasy": "奇幻",
    "Girls Love": "百合",
    "Gourmet": "美食",
    "Horror": "恐怖",
    "Mystery": "懸疑",
    "Romance": "戀愛",
    "Sci-Fi": "科幻",
    "Slice of Life": "日常",
    "Sports": "運動",
    "Supernatural": "超自然",
    "Suspense": "驚悚",

    // Demographics
    "Josei": "女性向",
    "Kids": "兒童",
    "Seinen": "青年",
    "Shoujo": "少女",
    "Shounen": "少年",

    // Themes
    "Adult Cast": "成人主角",
    "Anthropomorphic": "擬人化",
    "CGDCT": "美少女", // Cute Girls Doing Cute Things
    "Childcare": "育兒",
    "Combat Sports": "格鬥",
    "Crossdressing": "偽娘",
    "Delinquents": "不良少年",
    "Detective": "偵探",
    "Educational": "教育",
    "Gag Humor": "搞笑",
    "Gore": "獵奇",
    "Harem": "後宮",
    "High Stakes Game": "死亡遊戲",
    "Historical": "歷史",
    "Idols (Female)": "偶像(女)",
    "Idols (Male)": "偶像(男)",
    "Isekai": "異世界",
    "Iyashikei": "治癒",
    "Love Polygon": "多角戀",
    "Magical Sex Shift": "性轉換",
    "Mahou Shoujo": "魔法少女",
    "Martial Arts": "武術",
    "Mecha": "機甲",
    "Medical": "醫療",
    "Military": "軍事",
    "Music": "音樂",
    "Mythology": "神話",
    "Organized Crime": "黑道",
    "Otaku Culture": "御宅",
    "Parody": "惡搞",
    "Performing Arts": "表演藝術",
    "Pets": "寵物",
    "Psychological": "心理",
    "Racing": "賽車",
    "Reincarnation": "轉生",
    "Reverse Harem": "逆後宮",
    "Romantic Subtext": "曖昧",
    "Samurai": "武士",
    "School": "校園",
    "Showbiz": "演藝圈",
    "Space": "太空",
    "Strategy Game": "策略遊戲",
    "Super Power": "超能力",
    "Survival": "生存",
    "Team Sports": "團體運動",
    "Time Travel": "時空穿越",
    "Vampire": "吸血鬼",
    "Video Game": "遊戲世界",
    "Visual Arts": "視覺藝術",
    "Workplace": "職場",
    "Urban Fantasy": "都市奇幻"
};
